### ISSUE TITLE
RuntimeErrors and segfaults from swt2() in threaded environments

### ISSUE THREAD

**Issue by crowsonkb** [PyWavelets/pywt#288] opened 2017-02-28 20:46 UTC
The following code raises a RuntimeError ("C wavelet transform failed") not always but the vast majority of the time for me (macOS, PyWavelets 0.5.1):

```python
for _ in range(100):
    arrs = [np.eye(16) for _ in range(100)]
    with ThreadPoolExecutor() as ex:
        list(ex.map(partial(pywt.swt2, wavelet='haar', level=1), arrs))
```

swt2() in general seems likely to fail or segfault in multithreaded environments. Switching out the ThreadPoolExecutor for a ProcessPoolExecutor, for instance, makes it work reliably.

**Comment by grlee77** [comment] 2017-03-01 05:54
Thanks for reporting this.  I can confirm that this happens for me as well (only tried on OS X so far) for `swt`, `swt2` or `swtn`.  This same example works fine using DWT routines such as `wavedecn` instead.  Another hint is that it also works fine for `swt` **if the signals are 1D**.  This seems to point to something within the `swt_axis` Cython routine (as opposed to the 1D `swt` Cython routine which seems fine).

I will try to come up with a fix, but my available time is limited this week.

**Comment by grlee77** [comment] 2017-03-01 07:02
Took a quick look to track down where the exception originates in the C code.  It is being raised by the following shape check.
https://github.com/PyWavelets/pywt/blob/492c4343cc19ea1c6a5d77e35ef8851d2828b11e/pywt/_extensions/c/wt.template.c#L56-L57
When an exception was raised I found input_shape[0] was 16 as expected, but output_shape[0] was nonsensical values such as 659753992! 

I think the culprit may be the following lines:
https://github.com/PyWavelets/pywt/blob/492c4343cc19ea1c6a5d77e35ef8851d2828b11e/pywt/_extensions/_swt.pyx#L138-L141
when cA is reassigned later in the function, this original cA may get garbage collected leading to bad pointers in output_shape.  I have a fix that seems to be working locally and will make a PR.

**Closed** 2017-03-07 10:00 UTC
