### ISSUE TITLE
behavior of coeficients in discontinuities

### ISSUE THREAD

**Issue by Feulo** [PyWavelets/pywt#550] opened 2020-04-13 23:02 UTC
Hey there, 

I am trying to reproduce the example 6.2 from the book Discrete Fourier Analysis and Wavelets (S. Allen Broughton and Kurt Bryan). The example consists in the calculation of the approximation and detail coefficients for a 1D signal with some discontinuities. here is the base code I used:

```
N = 1024
# sinal com vários trechos independentes
x = np.zeros(1024)
x[0:350] = np.sin(2 * m.pi * 12 *  np.arange(0, 1, 1/N)[:350]) 
x[350:500] = 0.8 * np.ones(150)
x[500:800] = 0.3 * np.ones(300)

# passa-baixas
l = [0.5, 0.5]
xl = np.convolve(x, l)
# passa-altas
h = [0.5, -0.5]
xh = np.convolve(x,h)

fig, ax = plt.subplots(1,3, figsize=(18,4))
ax[0].plot(x)
ax[0].set_ylim([-1, 1])
ax[0].set_title("Sinal original");
ax[0].set_xlabel("amostras")
ax[0].set_ylabel('amplitude')
ax[1].plot(xl[0:N:2])
ax[1].set_ylim([-1, 1])
ax[1].set_title("Coeficientes de aproximacao")
ax[2].plot(xh[0:N:2])
ax[2].set_ylim([-1, 1])
ax[2].set_title("Coeficientes de detalhe")
plt.show()
```
and the corresponding image (similar to the book's image):
![fig1](https://user-images.githubusercontent.com/12126743/79168717-fa9ce300-7dc0-11ea-80cd-ebfcae304048.png)

As it is visible there are some non-zero coefficients in the detail part, corresponding to the discontinuities, but when I use the `dwt` function from `pywt` all coefficients are zero in the discontinuities, the result is the same for the built-in Haar Filters or the custom one's I created 

```
N = 1024
# sinal com vários trechos independentes
x = np.zeros(1024)
x[0:350] = np.sin(2 * m.pi * 12 *  np.arange(0, 1, 1/N)[:350]) 
x[350:500] = 0.8 * np.ones(150)
x[500:800] = 0.3 * np.ones(300)

dec_lo, dec_hi, rec_lo, rec_hi = [0.5, 0.5], [0.5, -0.5], [1, 1], [-1, 1] 
filter_bank = [dec_lo, dec_hi, rec_lo, rec_hi] 
haar_exemplo = pywt.Wavelet(name="myHaarWavelet", filter_bank=filter_bank) 
xl, xh = pywt.dwt(x, haar_exemplo, mode='zero')

fig, ax = plt.subplots(1,3, figsize=(18,4))
ax[0].plot(x)
ax[0].set_ylim([-1, 1])
ax[0].set_title("Sinal original");
ax[0].set_xlabel("amostras")
ax[0].set_ylabel('amplitude')
ax[1].plot(xl[0:N:2])
ax[1].set_ylim([-1, 1])
ax[1].set_title("Coeficientes de aproximacao")
ax[2].plot(xh[0:N:2])
ax[2].set_ylim([-1, 1])
ax[2].set_title("Coeficientes de detalhe")
plt.show()
```
![fig2](https://user-images.githubusercontent.com/12126743/79168852-43549c00-7dc1-11ea-88f0-bad43bb63898.png)

Is there a way to use the `dwt ` so I can get the same result as the example?

**Comment by grlee77** [comment] 2020-04-13 23:20
I think this has to do with the choice of whether to keep the even or odd samples during the downsampling step during the DWT.

For example, in the piecewise constant regions, convolving with the Haar filter will only give a single non-zero sample at those sharp edges and whether that transition happens to fall on and odd vs. even sample will determine whether it will show up in the detail coefficients.

In the following code fragment, I just shifted the locations of these step transitions to occur 1 sample earlier. In that case, you will see non-zero coefficients at the transitions.
```
N = 1024
# sinal com vários trechos independentes
x = np.zeros(1024)
x[0:349] = np.sin(2 * m.pi * 12 *  np.arange(0, 1, 1/N)[:349]) 
x[349:501] = 0.8 * np.ones(152)
x[501:801] = 0.3 * np.ones(300)

dec_lo, dec_hi, rec_lo, rec_hi = [0.5, 0.5], [0.5, -0.5], [1, 1], [-1, 1] 
filter_bank = [dec_lo, dec_hi, rec_lo, rec_hi] 
haar_exemplo = pywt.Wavelet(name="myHaarWavelet", filter_bank=filter_bank) 
xl, xh = pywt.dwt(x, haar_exemplo, mode='zero')
```

This type of effect is why the DWT is a "shift-variant" transform while the stationary wavelet transform (SWT) is "shift-invariant" (because SWT does not have the downsampling step).

**Comment by grlee77** [comment] 2020-04-13 23:21
Feel free to comment/ask for further clarification here, but I am going to close the issue as it is not a bug in PyWavelets.

**Closed by grlee77** 2020-04-13 23:21 UTC

**Comment by Feulo** [comment] 2020-04-18 00:35
Thank you! I just tried the first example keeping the odd samples in the downsampling steps and got the same results from the dwt. I have just one more question: Is there any reason for implementing the dwt keeping odd samples instead of even samples?
