### ISSUE TITLE
what is the scale function for the cwt

### ISSUE THREAD

**Issue by ZHANGGU** [PyWavelets/pywt#379] opened 2018-07-04 17:16 UTC
Hei gents

I see the scale array, and I tried many times using my data

1. once the wavelet is chosen as Morlet, what is the nondimensional frequency w? as CWT function, one can not setup this parameter
2. the scale if is a float that less than 1 e.g. 0.01273 (sampling period = 0.01), and I have seen that it could not give the wavelet  due to sampling rate, and therefore the error in extracting the number of samples after convolution will give an error.

This time domain CWT give limitations due to sampling rate, when the wavelet might not be obtained for convolution, am I right?

thanks a lot

**Comment by grlee77** [comment] 2018-07-05 16:51
I think you are asking about how to choose the `scales` argument to `cwt`?  

We don't have much CWT documentation currently, but what values are appropriate is going to depend on the signal you are analyzing.  There is one concrete example given here:
https://github.com/PyWavelets/pywt/blob/580d79d9440ec0f4f936892e39c79ad13a8fd33b/demo/cwt_analysis.py
The scales are closely related to the underlying frequency: see the function `pywt.scale2frequency` which is used to generate the `frequencies` array that is returned by the CWT.

The `cwt` function in PyWavelets is similar to the [CWT implementation in older versions of matlab](https://www.mathworks.com/help/wavelet/ref/cwtold.html). The documentation on scales at that link would apply equally to the CWT in PyWavelets.

**Comment by ZHANGGU** [comment] 2018-07-05 17:05
Thanks for your fast response. The cwt function today has bug, as I tested my signal with sampling frq 100Hz (sampling period = 0.01). I debugged into the function _cwt(), at a scale 0.01273, and then went to the convolve() function where I think the convolution with data signal and wavelet. 

   coef = - np.sqrt(scales[i]) * np.diff(np.convolve(data, int_psi[j.astype(np.int)][::-1]))
    d = (coef.size - data.size) / 2.
    out[i, :] = coef[int(np.floor(d)):int(-np.ceil(d))]

1. the wavele at this scale has only one sample namely {int_psi[j.astype(np.int)][::-1])}
2. after convolution, the output shall be extracted, given by "d", and then the error come due to not enough number of samples.

Plz have a look! Thanks a lot!

**Comment by grlee77** [comment] 2018-07-05 20:04
I think this may indeed be a bug with how `sampling_period` is handled.  Do things seem to work correctly if you leave `sampling_period=1.0` and then adjust scale to be 0.01273/0.01 = 1.273 instead?

**Comment by grlee77** [comment] 2018-07-05 21:53
After a bit more investigation, I think the problem here is that `scale` is defined in terms of a sampling_period equal to 1 rather than using the user-supplied `sampling_period`.

Here is a quick example of the sampled wavelet at different scales:
```python
import numpy as np
import pywt
import matplotlib.pyplot as plt

scales = [10, 1, 0.5, 0.1]
fig, axes = plt.subplots(len(scales), 1)

for n, scale in enumerate(scales):
    j = np.floor(
        np.arange(scale * (x[-1] - x[0]) + 1) / (scale * step))
    if np.max(j) >= np.size(int_psi):
        j = np.delete(j, np.where((j >= np.size(int_psi)))[0])    
    axes[n].plot(x[j.astype(np.int)], int_psi[j.astype(np.int)], '.-')
    axes[n].legend(['scale = {}'.format(scale)])
```

![scales](https://user-images.githubusercontent.com/6528957/42349554-24483b0e-807b-11e8-8661-b089a94320e5.png)

At the scale of 0.01273 used in your example this only results in a single sample in the sampled wavelet which leads to problems later on.

**Comment by grlee77** [comment] 2018-07-05 22:17
The behaviour documented above seems consistent with pre-2016 Matlab CWT which is what PyWavelets tests against.  The Matlab documentation also explicitly states that

```
"The samplingperiod is only used in the conversion of scales to frequencies. Specifying samplingperiod does not affect the appearance of plots generated by cwt."
```

**Comment by grlee77** [comment] 2018-07-05 23:07
See #381 for a documentation changes that will hopefully guide in choice of scales.  In your case, specified value of 0.01273 corresponds to a frequency of nearly 2 kHz (at least for the Mexican Hat wavelet) which is not a reasonable choice of scale for a signal sampled at 100 Hz.

```python
sampling_period = 0.01
f_Hz = pywt.scale2frequency('mexh', [0.01273]) / sampling_period
```

**Comment by ZHANGGU** [comment] 2018-07-06 04:46
ref. paper: A practical guide to wavelet analysis(C Torrence and G.P. Compo 1998).

Wavelet Morlet definition given in E.q. 1,where the frequncy number W0 defines the wavelet Fourier wavelength.
Lets say if W0=6 as suggested in the paper.

Given a scaling factor eg scale=0.01273, and then the frequency will be 6/(2*Pi*scale) = 7Hz.

Therefore I am interested in what is W0 in PYWT?

Secondly, the Morlet waveform seems not correct given in PYWT. Because, when scale = 0.01273, PYWT could not given the wavlet samples. But accoridng to E.q.1, there at least a wavelet.

INFO, Obspy.cwt has been tested and works well. While PYWT is more popular around discussions, it shall be notet that there is an bug.

**Comment by grlee77** [comment] 2018-07-06 06:09
> what is W0 in PYWT?

In release 0.5.2 it was hardcoded to a specific value.  If you build from current master or wait for the next release, it will be possible to specify the value within the wavelet name. 

The python code below is equivalent to the C code used for the Morlet wavelet (it is [from the tests](https://github.com/PyWavelets/pywt/blob/c2689f6f17006cf9b630d298a989cdcc7847275c/pywt/tests/test_cwt_wavelets.py#L84-L87)).  This form of the equation matches the convention used by Matlab.  

```python
def ref_cmor(LB, UB, N, Fb, Fc):
    x = np.linspace(LB, UB, N)
    psi = ((np.pi*Fb)**(-0.5))*np.exp(2j*np.pi*Fc*x)*np.exp(-(x**2)/Fb)
    return (psi, x)
```
The extent LB = -8.0 and UB = 8.0 and N = 2**10 are used during the CWT computations.  N is determined based on precision.  In release 0.5.2, `Fc=0.5` and `Fb=1.0`.

You can get these values via wavelet attributes:
```Python
wav = pywt.ContinousWavelet('cmor')
print(wav.center_frequency)
print(wav.bandwidth_frequency)
```

In current master you can instead specify the name as 'cmorB-C' where B is a float corresponding to `Fb` and C is a float corresponing to `Fc`.

**Comment by grlee77** [comment] 2018-07-06 15:59
> As said, currently pywt.cwt has bug in generating the wavelet. It could not handle the scaling factors as in the case I observed.

The expression in `ref_cmor` above looks equivalent to the equation you provided except for a difference in the normalization factor out front. I am still not convinced there is a bug.

Did you look at how `scales` relates to frequency in PyWavelets? Unless I am mistaken, your choice of `scales=0.01273` corresponds to a frequency of 3928 Hz (`pywt.scale2frequency('cmor', scale=0.01273, precision=10)`).  Why are you trying to analyze a signal sampled at 100 Hz at a frequency that is so far above the Nyquist rate? (The way `scales` is defined appears to lead to `scale=1` being approximately the Nyquist rate for the signal). This is unlikely to provide anything meaningfull. Are you sure you didn't mean to use `scale = 1.273` which would correspond to 39.28 Hz for the complex Morlet?

**Comment by ZHANGGU** [comment] 2018-07-06 16:59
See the equation, there is W0.

With the scale factor, the Fourier frequency will be around W0/(2*pi*a) for the sinus of Morlet, and this frquency is calculated for W0=6/(2*pi*0.01273)=75Hz, not 3928 Hz. See the paper "A practical guide to wavelet analysis(C Torrence and G.P. Compo 1998)". as Of course, this does not apply for the 100 Hz sampling frequency. I tried a=0.064, and then the frquency as calculated f=6/(2*3.14*0.064)=15 Hz, while the wavelet generator gives error.

**Comment by grlee77** [comment] 2018-07-06 17:11
It is true that the `scales` as defined in PyWavelets does not exactly correspond to `W0` in the equation.  This does not mean that the implementation in PyWavelets is incorrect, just that a different convention is being used to define the wavelet scales. As mentioned, above, to get 15 Hz in PyWavelets you should just need to choose the scale that causes `pywt.scale2frequency('cmor', scale) / sampling_period` to return 15 Hz.  The value you want for that case appears to be a scale of 3.33 when the sampling period is 0.01 s.  In other words, scale=3.33 in PyWavelets should be equivalent to W0=0.064 in the Torrence and Compo equation when `'cmor'` (specifically, `'cmor1.0-0.5'`) is used as the wavelet.

**Comment by ZHANGGU** [comment] 2018-07-06 17:18
Thanks. Due to documentation, I did not know that how but did choose the scale according the paper. Maybe it is good to polish the documentation. While using the equation might also be a good choice instead. Have a nice weekend!

**Comment by grlee77** [comment] 2018-07-06 17:29
I am going to close this as not a bug and have opened a new issue at #386 to remind us to work on the documentation going forward

**Closed by grlee77** 2018-07-06 17:29 UTC
