### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dmpetrov** [PyWavelets/pywt#180] opened 2016-07-04 09:33 UTC
It looks like pywt has a memory leak. When I process more than 200K small images (<10 KB each) a process takes all 16GB of my memory and stops (or slows down).

- Code

whash() function from imagehash lib:
https://github.com/JohannesBuchner/imagehash/pull/23/commits/da9386da76d3d32f6ba41160c7ef284102df36fc

Reproduction code snippet:
```
res = {}
i = 0
for filename in onlyfiles:
    fname = os.path.join(filedir, filename)
    try:
        image = PIL.Image.open(fname)
        whash = imagehash.whash(image)
        value = whash.hash.flatten()
        res[int(filename[:-4])] = sum(1<<i for i, b in enumerate(value) if b)
    except Exception as e:
        print("Error. File " + fname + ": ", e )
```

Btw.. imagehash.phash() function doesn't use pywt and doesn't have this issue.

- Data

Image subset from Avito competition:
https://www.kaggle.com/c/avito-duplicate-ads-detection

**Comment by JohannesBuchner** [comment] 2016-07-04 09:49
Perhaps it is more helpful to write a test case code which does not use imagehash to show that the issue is indeed in pywt.

**Comment by JohannesBuchner** [comment] 2016-07-04 09:49
Does the memory leak for all kinds of modes/methods or only one in particular?

**Comment by JohannesBuchner** [comment] 2016-07-04 10:01
Candidates could be these two functions, which allocate a Wavelet object, and one should double-check that these are being de-allocated.

wavedec2
https://github.com/PyWavelets/pywt/blob/416c697d612ac75acfc3a216a193b2582701b62b/pywt/_multilevel.py

idwtn
https://github.com/PyWavelets/pywt/blob/416c697d612ac75acfc3a216a193b2582701b62b/pywt/_multidim.py

**Comment by dmpetrov** [comment] 2016-07-04 11:23
Reproduction code snippet without imagehash (files - list of input files, 200K+ files):
```
mode = 'haar'
level = 3
image_scale = 32
ll_max_level = int(numpy.log2(image_scale))
dwt_level = ll_max_level - level

for fname in files:
        image = PIL.Image.open(fname)
        image = image.convert("L").resize((image_scale, image_scale), PIL.Image.ANTIALIAS)
        pixels = numpy.array(image.getdata(), dtype=numpy.float).reshape((image_scale, image_scale))
        pixels /= 255
        coeffs = pywt.wavedec2(pixels, mode, level = dwt_level)
        dwt_low = coeffs[0]
        med = numpy.median(dwt_low)
        diff = dwt_low > med
        # Ignore result
```

I saw the leaking issue with 'haar' and 'db4' modes.

**Comment by kwohlfahrt** [comment] 2016-07-04 15:41
Can reproduce, will investigate.

```
import numpy as np
import pywt

for i in range(100000):
    pixels = np.ones((32, 32), dtype=np.float)
    pywt.wavedec2(pixels, 'haar', 5)
```

Throwing in a `gc.collect()` doesn't help.

**Comment by kwohlfahrt** [comment] 2016-07-04 22:48
Gotcha. It's these two lines in `dwt_axis` responsible, I'll figure out what to do about them in the morning.

```
    output_shape = (<size_t [:data.ndim]> <size_t *> data.shape).copy()
    output_shape[axis] = common.dwt_buffer_length(data.shape[axis], wavelet.dec_len, mode)
```

**Comment by stuaxo** [comment] 2016-07-05 22:39
Is that a known issue in Cython ?   Could be worth raising it there ?

**Comment by kwohlfahrt** [comment] 2016-07-06 10:57
@stuaxo yes, I will raise it upstream, I have a minimal example [here](https://gist.github.com/kwohlfahrt/3711fd519146cd5bb10872b6668b1560). http://trac.cython.org is dead at the moment though.

**Comment by stuaxo** [comment] 2016-07-06 15:20
Cheers :) only mentioned as it gave me a horrible flashback to a similar bug I had before, but never tracked down in a different library.

**Comment by kwohlfahrt** [comment] 2016-07-06 20:27
@dmpetrov could you double check that this is fixed now?

**Comment by dmpetrov** [comment] 2016-07-07 06:56
I've checked the master branch version. Now it works much better. For one specific scenario it uses 400MB instead of 1.2GB of RAM.

However, the memory usage is still increasing. The growth rate is 3-10 times less then it use to be. I'm not sure if it is another issue in the library or just a regular Python behavior.

Anyway now we can process million of images with less then 1Gb of memory (less than 700MB to be precise). So, I think we can close the issue.

**Comment by kwohlfahrt** [comment] 2016-07-07 12:59
That still shouldn't be happening. I'll re-open this so I remember to chase it down.

**Comment by JohannesBuchner** [comment] 2016-07-07 14:02
@dmpetrov, could you try to do `gc.collect()` in your loop?

**Comment by dmpetrov** [comment] 2016-07-07 14:59
I'll try today night.

**Comment by dmpetrov** [comment] 2016-07-08 03:46
tried gc() in the loop - the same result

**Comment by kwohlfahrt** [comment] 2016-07-08 13:01
I am unable to reproduce the issue with the following script, with 10 000 000 loop iterations memory use stays constant. Perhaps the bug is in PIL.

```
#!/usr/bin/env python3

import numpy as np
import pywt
import sys

mode = 'haar'
level = 3
image_scale = 32
ll_max_level = int(np.log2(image_scale))
dwt_level = ll_max_level - level

for _ in range(int(sys.argv[1])):
    pixels = np.ones((image_scale, image_scale), dtype="float")
    coeffs = pywt.wavedec2(pixels, mode, level = dwt_level)
    dwt_low = coeffs[0]
    med = np.median(dwt_low)
    diff = dwt_low > med
    # Ignore result
```

**Comment by dmpetrov** [comment] 2016-07-08 13:41
@kwohlfahrt you are right. I replaced image reading part to image copy and now the memory usage is constant.

Do you know where is the correct PIL repository for opening a bug https://github.com/python-pillow/Pillow ?

**Comment by kwohlfahrt** [comment] 2016-07-08 14:41
That looks like the right place (if you are using pillow instead of the old PIL). I haven't used it much to be honest. Closing this now, thanks for reporting and following up :)

**Closed by kwohlfahrt** 2016-07-08 14:41 UTC
Labels: bug

**Comment by dmpetrov** [comment] 2016-07-08 14:47
Thank you for the fix!

**Comment by dmpetrov** [comment] 2016-07-08 15:17
I reported the bug to Pillow: https://github.com/python-pillow/Pillow/issues/2019
