### ISSUE TITLE
Compiler support

### ISSUE THREAD

**Issue by kwohlfahrt** [PyWavelets/pywt#75] opened 2015-07-26 15:36 UTC
Which C compilers should we fully support? [Numpy](http://docs.scipy.org/doc/numpy/user/install.html) and [Scipy](http://www.scipy.org/scipylib/building/windows.html) both recommend GCC, and state other compilers are not supported, but this documentation appears dated (references to Python 2.4, which had it's final release 7 years ago).

I had a quick look at what the current packages look like in the table below. Essentially, every platform but CentOS supports C11 in its latest LTS release:

| OS | Compiler | C standard |
| --- | --- | --- |
| CentOS 6 | gcc-4.4 | C99 |
| CentOS 7 | gcc-4.8 | C99 |
| Debian 7 | gcc-4.6 | C99 |
| Debian 8 | gcc-4.9 | C11 |
| Ubuntu 12.04 | gcc-4.6 | C99 |
| Ubuntu 15.04 | gcc-4.9 | C11 |
| Fedora 21 | gcc-4.9 | C11 |
| Fedora 22 | gcc-5.1 | C11 |
| Windows Python <= 3.2 | VS 2008 | C89 |
| Windows Python <= 3.4 | VS 2010 | C89 |
| Windows Python >= 3.5 | VS 2015 | C99 |
| MinGW-w64 | gcc-5.1 | C11 |
| Cygwin | gcc-4.9 | C11 |

I've been fighting to test Visual Studio, since we have no CI support for it. It has been fairly difficult get a working Visual Studio 2010 installation (the activation button in the installer leads to a dead URL). There is a VS 2008 version out there explicitly for Python 2.7 support, but this is 7 years old! Visual Studio 2013 and up also support using clang as a compiler.

C11 support would get us `_Generic`, which could be very helpful for avoiding blocks like:

```
if data.dtype == numpy.float64:
    double_thing(data)
elif data.dtype == numpy.float43:
    float_thing(data)
```

Personally, given it's age, lag in supporting C standards, and especially the lack of CI support, I would advocate dropping or at least deprecating MSVC. Clang distributes a windows binary now, plus there are always the options of mingw and cygwin. We would however lose support for creating binary distributions for windows.

Comments, especially from @rgommers?

This isn't a priority, but testing MSVC is proving difficult, and having to remind myself to stick to C89 all the time is annoying so I thought I'd put the idea out there.

**Comment by rgommers** [comment] 2015-07-26 18:47
@kwohlfahrt very good point, we should clearly document this and where possible improve the CI setup.

Numpy and Scipy definitely (have to) support multiple compilers; the documentation may be out of date in places. I'd suggest the following:

Windows: 
- MSVC
- MinGW-w64 (https://github.com/numpy/numpy/wiki/Mingw-w64-faq)
- MinGW32 (https://github.com/numpy/numpy-vendor)

Linux:
- all GCC versions >= 4.4

OS X:
- Clang
- GCC

Probably will work and we'll accept patches for them but we won't bother to test:
- ICC
- PathScale
- Cygwin
- Default compilers on other platforms (Raspberry Pi, AIX, Solaris, etc.)

**Comment by rgommers** [comment] 2015-07-26 18:48
Also I'd consider Cython a compiler, not a Python package/dependency. As long as things work for the latest stable Cython release then I'm happy.

**Comment by rgommers** [comment] 2015-07-26 18:49
Appveyor doesn't work well for numpy (fuzzy reasons) and scipy (no Fortran compiler), but may work for pywt. I'll give that a quick try - that would be low-maintenance MSVC CI.

**Comment by rgommers** [comment] 2015-07-26 19:37
@kwohlfahrt dropping support for MSVC is unfortunately pretty much impossible. MinGW has its own share of issues; Anaconda and Enthought both use MSVC for their whole stack so it's the default compiler for a large part of the community.

Some background: part of the problem is when you throw Fortran code into the mix (like Scipy does). MSVC + Intel ifort + Intel MKL is a solid combination; MinGW gcc + gfortran is still basically unusable. Hence MSVC cannot be ignored.

**Comment by kwohlfahrt** [comment] 2015-07-27 13:39
Ah I see. I hadn't considered Anaconda & co, I've never used them. I have almost no experience developing for python in Windows, so I'll leave it in your hands. Having good test coverage on Windows would go a long way though, thanks for looking into it.

**Comment by rgommers** [comment] 2015-07-27 14:58
I prefer to compile the whole stack myself on Linux and OS X, but when I'm forced to use Windows then Anaconda is a lifesaver.

gh-76 is ready to merge I think and takes care of Windows test coverage.

**Comment by kwohlfahrt** [comment] 2015-08-07 15:08
OK, so current status is GCC 4.4, Clang (version?), and MSVC 2008? And we have integration tests for GCC and MSVC.

We could add clang to Travis CI, and then close this?

**Comment by grlee77** [comment] 2015-08-07 15:59
I don't know much about clang, but it looks like version 1.0 was as recent as Oct 2009.  As far as I can tell it has always had C99 support and currently has C11 as the default.

**Comment by rgommers** [comment] 2015-08-13 20:37
I'm not sure how much it helps to add Clang on Linux, because that'll be quite different from OS X. The issues on OS X are usually related to where MacPorts/Homebrew hide their headers, Accelerate issues (not applicable for pywt), etc.

It doesn't hurt either though, so if there's an easy recipe to steal to test with Clang on TravisCI then why not.

**Comment by rgommers** [comment] 2015-08-13 20:38
I use Clang on OS X regularly by the way. And since an OS X buildbot will be a massive pain, I would suggest to close this issue by simply documenting the supported compilers and testing Clang once in a while (especially before a release).

**Comment by grlee77** [comment] 2015-12-16 21:36
@kwohlfahrt
Can you check/update the compiler information in `doc/source/dev/preparing_windows_build_environment.rst` and `README.rst`?

**Comment by kwohlfahrt** [comment] 2015-12-17 16:28
I don't think anything was incorrect, but I've filled in information for newer python binaries in #145

**Closed** 2016-12-31 17:59 UTC
Labels: documentation, needs-decision, task
