### ISSUE TITLE
wavelet test - python result differs from R

### ISSUE THREAD

**Issue by geraldstanje** [PyWavelets/pywt#186] opened 2016-08-08 21:13 UTC
Hi,

I want to port some R code which includes a wavelet transform to Python:

r code:
https://gist.github.com/geraldstanje/a0ad53b7cb7828f1999ee9693df3a75e

python code:
https://gist.github.com/geraldstanje/7bcd560af208a86352adfe4ed5a38202

can you explain why the python version returns a different result?

here is the input file:
https://gist.github.com/geraldstanje/52a4fb141e124da3da2249654eb6b91d

```
$ python main.py
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]
$ Rscript main.R
Loading required package: methods
          [,1]      [,2]      [,3]    [,4]     [,5]      [,6]      [,7]
[1,] -1.173323 -1.651935 -2.566267 0.68943 1.976365 -2.668054 -1.332537
          [,8]
[1,] -2.423402
```

info regarding the dwt function in R:
Slot "V": A list with element i comprised of a matrix containing the ith level scaling
coefficients

**Comment by kwohlfahrt** [comment] 2016-08-09 09:36
I suspect this is due to the boundary condition. `'zpd'` specifies you want to treat the array as though it was zero-padded, while according to the [wavelet package reference](http://pywavelets.readthedocs.io/en/latest/ref/signal-extension-modes.html) R only supports periodic and reflection boundary conditions. You can find more info on boundary conditions supported by pywt [here](http://pywavelets.readthedocs.io/en/latest/ref/signal-extension-modes.html).

**Comment by geraldstanje** [comment] 2016-08-09 13:57
@kwohlfahrt is seems the mode does not effect the result. I extract the scaling coefficients in R. Is it the right way I extract them in Python as well?
```
result with mode='symmetric':
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]

result with mode='periodic':
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]

result with mode='periodization':
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]

result with mode='smooth':
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]

result with mode='constant':
[[-1.17332339 -1.65193486 -2.39370823 -2.61983228 -0.85778236  0.09582752
  -1.69595575 -2.26903105]]
```

**Comment by geraldstanje** [comment] 2016-08-11 04:20
@kwohlfahrt did you already have time to look at it?

**Comment by kwohlfahrt** [comment] 2016-08-11 11:32
No, sorry. I'm very busy writing up at the moment, so can't commit time to look into this deeply in the immediate future.

**Comment by geraldstanje** [comment] 2016-08-12 17:08
someone else who can give feedback?

**Comment by grlee77** [comment] 2016-08-12 21:08
Hi @geraldstanje,

I am not sure exactly what your goal is here with keeping the first coefficient of the approximation coefficient array at each level, but the following code does what you want.  It is not computationally efficient, but depending on your data size that may or may not matter.  It uses wavedecn to do 1 1-level decomposition,  restarts with a 2-level decomposition, etc...

If you look at the internals of `pywt.wavedec` you could modify it to avoid the redundant computations.  This does match the output from R above as is, though

```python
acoeffs = [pywt.wavedec(df['2'], 'haar', 'periodic', level=l)[0][0] for l in range(1, 9)]
print(acoeffs)
```
```
 [-1.1733234, -1.6519349, -2.3937082, -2.6198323, -0.85778236, 0.09582752, -1.6959558, -2.269031]
```

**Comment by grlee77** [comment] 2016-08-12 21:14
As an aside, it is good to see that the `pywt` functions work properly for the `pandas.series.Series` inputs used in this example.  That is not something we explicitly test against as far as I can recall, but the call to `np.asarray` seems to take care of the conversion.

**Comment by geraldstanje** [comment] 2016-08-12 22:21
@grlee77 my goal is to port the R code of the wavelet transform to python to extract the scaling coefficients. Im not sure if I do it in the right way in python?

**Comment by geraldstanje** [comment] 2016-08-17 21:28
@grlee77 do you see the diff?

**Comment by grlee77** [comment] 2016-08-17 23:06
sorry, I had not noticed only the first couple of values were the same.  

At level 1 the input is size 380.  At level 2 it is 190.  Both of these are even length and the results match.  At level 3, the input is size 95 which is odd and this is where the differences start.  

This appears to be a difference in how R is handling the convolution for odd length inputs.  The implementation in PyWavelets is tested vs. outputs from Matlab's DWT and is not guaranteed to exactly match the implementation in R.

If you do the transform as follows, you can reproduce the numbers from R.  This requires manual periodic padding up to even size followed by removal of the padded element whenever the input array has odd length:
```python
acoeffs = []
a = np.asarray(df['2'])  # the data from your example
for i in range(1, 9):
    if len(a) % 2:
        a = np.concatenate(([a[-1]], a))  # prepend periodic sample to give an even length
        a, d = pywt.dwt(a, 'haar', 'periodic', 0)
        a = a[1:]  # remove the first sample of the output
        d = d[1:]
    else:
        a, d = pywt.dwt(a, 'haar', 'periodic', 0)
    acoeffs.append(a[0])
print(acoeffs)
```

To figure out why this is necessary would require comparing the source code in R to see exactly what the padding conventions are.  If you are so inclined, the relevant convolution routine used in PyWavelets is here:
https://github.com/PyWavelets/pywt/blob/5fc0f769dfdd6d21c2d0b2fa4fa8cdb7e887bb9f/pywt/_extensions/c/convolution.template.c#L107

**Comment by grlee77** [comment] 2016-08-17 23:07
as this does not appear to be a bug in `PyWavelets` I am going to close the issue.

**Closed by grlee77** 2016-08-17 23:07 UTC

**Comment by Arnold1** [comment] 2016-10-19 21:02
@grlee77 thanks for the info.

i wonder how the following version can be improved?
```
def next_pow(x):
  return int(2**math.ceil(math.log(x, 2)))

def wavedec2(data):
  acoeffs = []
  a = np.asarray(data)

  pow_two = next_pow(len(a))

  diff = pow_two - len(a)
  if diff > 0:
    a = np.concatenate((a, [0] * diff))

  for i in range(1, 5):
    if len(a) % 2:
      a = np.concatenate(([a[-1]], a))  # prepend periodic sample to give an even length
      a, d = pywt.dwt(a, 'haar', 'periodic', 0)
      a = a[1:]  # remove the first sample of the output
      d = d[1:]
    else:
      a, d = pywt.dwt(a, 'haar', 'periodic', 0)

    acoeffs.append(a[0])

  return acoeffs
```

**Comment by guigaoliveira** [comment] 2018-06-01 21:23
"a = a[1:]  # remove the first sample of the output" Why this is necessary?
