### ISSUE TITLE
questions about the WaveletPacket function

### ISSUE THREAD

**Issue by hjzSky** [PyWavelets/pywt#481] opened 2019-04-03 12:28 UTC
shouldn't the Wavelet packet decomposition function-WaveletPackt contain a parameter about sample frequency？ otherwise the wavelet coefficients' length of each level  will be vary along with the input length. But no matter what the input length is, as long as the sample frequency is fixed，should the wavelet coefficient length not change?

**Comment by grlee77** [comment] 2019-04-03 14:13
We can discuss this in the thread you started on the mailing list:
https://groups.google.com/forum/#!topic/pywavelets/aeZmmySgOas

It is not a bug in PyWavelets, so I will close the issue here

**Closed by grlee77** 2019-04-03 14:13 UTC
