### ISSUE TITLE
fbsp_order

### ISSUE THREAD

**Issue by tanjosh** [PyWavelets/pywt#283] opened 2017-02-16 12:06 UTC
Does it have built in function for Mallat's fast algorithm for quadratic spline wavelets (Characterization of signals from multiscale edges, 1992)?

**Comment by grlee77** [comment] 2017-03-01 17:36
It does not.  I do not have time to go through that paper at the moment, but based on a brief look at Appendix A, if it is a standard DWT but with filters as defined in Table 1, you can try defining your own wavelet filterbank based on that.  You would have to then manually apply any level-specific normalization coefficients as in Table 2 as there is not a built-in way to do that.

**Comment by grlee77** [comment] 2017-03-01 19:57
closing this as not a bug.  In the future, please direct this sort of query to the mailing list at:
https://groups.google.com/forum/#!forum/pywavelets

**Closed by grlee77** 2017-03-01 19:57 UTC
