### ISSUE TITLE
miss Calculation?

### ISSUE THREAD

**Issue by Decapitary** [PyWavelets/pywt#185] opened 2016-08-01 09:41 UTC
I calculated [1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8]`s DWT using D4 (aka db2) with this [equation](http://www.bearcave.com/misl/misl_tech/wavelets/matrix/daubeqn.jpg) the result is

my calculation in JS:
> Scaling [2.310789034541149, 5.139216159287339, 7.96764328403353, 10.038195644853694, 2.310789034541149, 5.139216159287339, 7.96764328403353, 10.038195644853694, 2.310789034541149, 5.139216159287339, 7.96764328403353, 10.038195644853694, 2.310789034541149, 5.139216159287339]
> Wavelet[2.220446049250313e-16, 4.440892098500626e-16, 4.440892098500626e-16, -2.8284271247461903, 2.220446049250313e-16, 4.440892098500626e-16, 4.440892098500626e-16, -2.8284271247461903, 2.220446049250313e-16, 4.440892098500626e-16, 4.440892098500626e-16, -2.8284271247461903, 2.220446049250313e-16, 4.440892098500626e-16]
Your output:
> >>> pywt.dwt([1,2,3,4,5,6,7,8,1, 2, 3 , 4 , 5, 6, 7 ,8],'db2')

> (array([  1.76776695,   2.31078903,   5.13921616,   7.96764328,  10.03819564,   2.31078903,  5.13921616,   7.96764328,  10.96015511]), 
> array([ -6.12372436e-01,  -9.90180160e-13,  -9.90874049e-13,  -9.89874849e-13,  -2.82842712e+00,  -9.90180160e-13, -9.90874049e-13,  -9.89874849e-13,   6.12372436e-01]))

Which one is correct?  what is your algorithm ? I know your filter coefs are right but how do you calculate this coefs?

**Comment by grlee77** [comment] 2016-08-01 18:33
I am closing this as it is not a bug.

Please use the [mailing list](https://groups.google.com/forum/#!forum/pywavelets) rather than the github issues page for general questions such as this.  

The implementation in PyWavelets is via (downsampled) convolution with the wavelet coefficient filter banks.

The cython code called by the `dwt` python function is here:
https://github.com/PyWavelets/pywt/blob/5fc0f769dfdd6d21c2d0b2fa4fa8cdb7e887bb9f/pywt/_extensions/_dwt.pyx#L22

That cython code calls C functions defined in `wt.c.template`
`https://github.com/PyWavelets/pywt/blob/5fc0f769dfdd6d21c2d0b2fa4fa8cdb7e887bb9f/pywt/_extensions/c/wt.template.c#L273

which call the convolution routines from `convolution.c.template`
https://github.com/PyWavelets/pywt/blob/5fc0f769dfdd6d21c2d0b2fa4fa8cdb7e887bb9f/pywt/_extensions/c/convolution.template.c#L107

The convolution code is a bit complicated due to the variety of different edge handling modes implemented.

The wavelet coefficients themselves are defined here:
https://github.com/PyWavelets/pywt/blob/5fc0f769dfdd6d21c2d0b2fa4fa8cdb7e887bb9f/pywt/_extensions/c/wavelets_coeffs.template.h

**Closed by grlee77** 2016-08-01 18:33 UTC

**Comment by Decapitary** [comment] 2016-08-01 20:45
sorry for that. the convolution code was perfectly clear (specially the
document comment). I used exactly this

**Comment by Decapitary** [comment] 2016-08-01 20:46
output[o] = sum(filter[j] * input[i-j] for j = [0..F) and i = [0..N))

in my code. should I do it your way or this is enough ?
